version: '3'

services:
  front-end:
    image: wrj95/frontendtcc:1.0
    container_name: Tatooine
    networks:
      frontend:
        ipv4_address: '10.1.1.5'
      backend:
        ipv4_address: '10.1.1.11'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node_app
  node_app:
    image: wrj95/backendtcc:1.0
    command: node app.js
    tty: true
    stdin_open: true
    container_name: node_app
    environment:
      - DB_HOST=mysql_app
      - DB_USER=root
      - DB_PASS=yourpassword
      - DB_DATABASE=mydatabase
      - PORT=3050
      - SECRET_KEY=TccUnip2018!
    expose:
      - 3050
    ports:
      - 3050:3050
    networks: 
      backend:
        ipv4_address: '10.1.1.10'
      database:
        ipv4_address: '10.1.1.19'
    depends_on:
      - mysql_app
  mysql_app:
    image: mysql:5.7
    container_name: mysql_app
    tty: true
    stdin_open: true
    networks: 
      database:
        ipv4_address: '10.1.1.20'
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_USER=user
networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/29
  backend:
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.8/29
  database:
    ipam: 
      driver: default
      config: 
      - subnet: 10.1.1.16/29