FROM node:latest

LABEL maintainer="Gabriel Pellegrini"

ENV HOME=/home/api

WORKDIR $HOME/portal

COPY . $HOME/portal

RUN npm i npm 

RUN npm install npm

RUN npm install consign

RUN npm install -g nodemon

RUN npm install express 

RUN npm install mysql




